//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Rower_Miejski
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Baza_Rower_MiejskiEntities : DbContext
    {
        public Baza_Rower_MiejskiEntities()
            : base("name=Baza_Rower_MiejskiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Funkcje_Pracownikow> Funkcje_Pracownikow { get; set; }
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Rowery> Rowery { get; set; }
        public virtual DbSet<Serwis_roweru> Serwis_roweru { get; set; }
        public virtual DbSet<Stan_roweru> Stan_roweru { get; set; }
        public virtual DbSet<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
