//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Rower_Miejski
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rowery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rowery()
        {
            this.Serwis_roweru = new HashSet<Serwis_roweru>();
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
        }
    
        public int ID_roweru { get; set; }
        public string Nr_ramy { get; set; }
        public Nullable<System.DateTime> Data_wprowadzenia_roweru_do_uzytku { get; set; }
        public Nullable<int> ID_stanu_FK { get; set; }
    
        public virtual Stan_roweru Stan_roweru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serwis_roweru> Serwis_roweru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
